name: Deploy Kubernetes Pod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Pod
        run: |
         kubectl apply -f k8s/pod.yaml
         kubectl apply -f k8s/deployment.yaml
